/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authCenteredRouteImport } from './routes/(auth)/_centered'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedAuditTrailsIndexRouteImport } from './routes/_authenticated/audit-trails.index'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated/users.create'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedAuditTrailsAuditTrailIdRouteImport } from './routes/_authenticated/audit-trails.$auditTrailId'
import { Route as authCenteredResetPasswordRouteImport } from './routes/(auth)/_centered.reset-password'
import { Route as authCenteredForgotPasswordRouteImport } from './routes/(auth)/_centered.forgot-password'
import { Route as authCenteredAuthVerificationRouteImport } from './routes/(auth)/_centered.auth-verification'
import { Route as authCenteredAuthErrorRouteImport } from './routes/(auth)/_centered.auth-error'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './routes/_authenticated/users.$userId_.edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authCenteredRoute = authCenteredRouteImport.update({
  id: '/(auth)/_centered',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditTrailsIndexRoute =
  AuthenticatedAuditTrailsIndexRouteImport.update({
    id: '/audit-trails/',
    path: '/audit-trails/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAuditTrailsAuditTrailIdRoute =
  AuthenticatedAuditTrailsAuditTrailIdRouteImport.update({
    id: '/audit-trails/$auditTrailId',
    path: '/audit-trails/$auditTrailId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const authCenteredResetPasswordRoute =
  authCenteredResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => authCenteredRoute,
  } as any)
const authCenteredForgotPasswordRoute =
  authCenteredForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authCenteredRoute,
  } as any)
const authCenteredAuthVerificationRoute =
  authCenteredAuthVerificationRouteImport.update({
    id: '/auth-verification',
    path: '/auth-verification',
    getParentRoute: () => authCenteredRoute,
  } as any)
const authCenteredAuthErrorRoute = authCenteredAuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => authCenteredRoute,
} as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/users/$userId_/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/patients': typeof AuthenticatedPatientsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/about': typeof PublicAboutRoute
  '/auth-error': typeof authCenteredAuthErrorRoute
  '/auth-verification': typeof authCenteredAuthVerificationRoute
  '/forgot-password': typeof authCenteredForgotPasswordRoute
  '/reset-password': typeof authCenteredResetPasswordRoute
  '/audit-trails/$auditTrailId': typeof AuthenticatedAuditTrailsAuditTrailIdRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/audit-trails/': typeof AuthenticatedAuditTrailsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/patients': typeof AuthenticatedPatientsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/about': typeof PublicAboutRoute
  '/auth-error': typeof authCenteredAuthErrorRoute
  '/auth-verification': typeof authCenteredAuthVerificationRoute
  '/forgot-password': typeof authCenteredForgotPasswordRoute
  '/reset-password': typeof authCenteredResetPasswordRoute
  '/audit-trails/$auditTrailId': typeof AuthenticatedAuditTrailsAuditTrailIdRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/audit-trails': typeof AuthenticatedAuditTrailsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/(auth)/_centered': typeof authCenteredRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/': typeof PublicIndexRoute
  '/(auth)/_centered/auth-error': typeof authCenteredAuthErrorRoute
  '/(auth)/_centered/auth-verification': typeof authCenteredAuthVerificationRoute
  '/(auth)/_centered/forgot-password': typeof authCenteredForgotPasswordRoute
  '/(auth)/_centered/reset-password': typeof authCenteredResetPasswordRoute
  '/_authenticated/audit-trails/$auditTrailId': typeof AuthenticatedAuditTrailsAuditTrailIdRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/audit-trails/': typeof AuthenticatedAuditTrailsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/users/$userId_/edit': typeof AuthenticatedUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/patients'
    | '/profile'
    | '/about'
    | '/auth-error'
    | '/auth-verification'
    | '/forgot-password'
    | '/reset-password'
    | '/audit-trails/$auditTrailId'
    | '/dashboard/settings'
    | '/users/$userId'
    | '/users/create'
    | '/audit-trails/'
    | '/users/'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/patients'
    | '/profile'
    | '/about'
    | '/auth-error'
    | '/auth-verification'
    | '/forgot-password'
    | '/reset-password'
    | '/audit-trails/$auditTrailId'
    | '/dashboard/settings'
    | '/users/$userId'
    | '/users/create'
    | '/audit-trails'
    | '/users'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/(auth)/_centered'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/_authenticated/dashboard'
    | '/_authenticated/patients'
    | '/_authenticated/profile'
    | '/_public/about'
    | '/_public/'
    | '/(auth)/_centered/auth-error'
    | '/(auth)/_centered/auth-verification'
    | '/(auth)/_centered/forgot-password'
    | '/(auth)/_centered/reset-password'
    | '/_authenticated/audit-trails/$auditTrailId'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/users/$userId'
    | '/_authenticated/users/create'
    | '/_authenticated/audit-trails/'
    | '/_authenticated/users/'
    | '/_authenticated/users/$userId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  authCenteredRoute: typeof authCenteredRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_centered': {
      id: '/(auth)/_centered'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authCenteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-trails/': {
      id: '/_authenticated/audit-trails/'
      path: '/audit-trails'
      fullPath: '/audit-trails/'
      preLoaderRoute: typeof AuthenticatedAuditTrailsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/audit-trails/$auditTrailId': {
      id: '/_authenticated/audit-trails/$auditTrailId'
      path: '/audit-trails/$auditTrailId'
      fullPath: '/audit-trails/$auditTrailId'
      preLoaderRoute: typeof AuthenticatedAuditTrailsAuditTrailIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/_centered/reset-password': {
      id: '/(auth)/_centered/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authCenteredResetPasswordRouteImport
      parentRoute: typeof authCenteredRoute
    }
    '/(auth)/_centered/forgot-password': {
      id: '/(auth)/_centered/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authCenteredForgotPasswordRouteImport
      parentRoute: typeof authCenteredRoute
    }
    '/(auth)/_centered/auth-verification': {
      id: '/(auth)/_centered/auth-verification'
      path: '/auth-verification'
      fullPath: '/auth-verification'
      preLoaderRoute: typeof authCenteredAuthVerificationRouteImport
      parentRoute: typeof authCenteredRoute
    }
    '/(auth)/_centered/auth-error': {
      id: '/(auth)/_centered/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof authCenteredAuthErrorRouteImport
      parentRoute: typeof authCenteredRoute
    }
    '/_authenticated/users/$userId_/edit': {
      id: '/_authenticated/users/$userId_/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAuditTrailsAuditTrailIdRoute: typeof AuthenticatedAuditTrailsAuditTrailIdRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedAuditTrailsIndexRoute: typeof AuthenticatedAuditTrailsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAuditTrailsAuditTrailIdRoute:
    AuthenticatedAuditTrailsAuditTrailIdRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedAuditTrailsIndexRoute: AuthenticatedAuditTrailsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface authCenteredRouteChildren {
  authCenteredAuthErrorRoute: typeof authCenteredAuthErrorRoute
  authCenteredAuthVerificationRoute: typeof authCenteredAuthVerificationRoute
  authCenteredForgotPasswordRoute: typeof authCenteredForgotPasswordRoute
  authCenteredResetPasswordRoute: typeof authCenteredResetPasswordRoute
}

const authCenteredRouteChildren: authCenteredRouteChildren = {
  authCenteredAuthErrorRoute: authCenteredAuthErrorRoute,
  authCenteredAuthVerificationRoute: authCenteredAuthVerificationRoute,
  authCenteredForgotPasswordRoute: authCenteredForgotPasswordRoute,
  authCenteredResetPasswordRoute: authCenteredResetPasswordRoute,
}

const authCenteredRouteWithChildren = authCenteredRoute._addFileChildren(
  authCenteredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  authCenteredRoute: authCenteredRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
